spring:
  datasource:
    url: ${MONITOR_SENSORS_SPRING_DATASOURCE_URL:jdbc:postgresql://monitor-sensors-postgres:5432/monitor_sensors}
    username: ${MONITOR_SENSORS_SPRING_DATASOURCE_USERNAME:postgres}
    password: ${MONITOR_SENSORS_SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

auth:
  jwt-expiration-time: ${MONITOR_SENSORS_JWT_EXPIRATION_TIME:1D}
  key-store: classpath:agsr-keystore.jks
  store-password: agsr-ks-password
  key-password: agsr-password
  alias: agsr-keystore
